services:
  api:
    build:
      context: ./apps/items-api
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  bff:
    build:
      context: ./apps/store-bff
      dockerfile: Dockerfile
    environment:
      DISCOVERY_URL: http://discovery:8080
      ENVIRONMENT: dev
      BACKEND_URL: http://api:8080
      K_SERVICE: local
    links:
      - api
      - discovery
    ports:
      - "8080:8080"

  discovery:
    build:
      context: ../run-service-discovery
      dockerfile: Dockerfile
    environment:
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    ports:
      - "8081:8080"


