runtime: go122
instance_class: F1
app_engine_apis: true
service: store-frontend
service_account: changeme_email

env_variables:
  DISCOVERY_URL: changeme_url

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

automatic_scaling:
  max_instances: 1
  min_instances: 0
